// Code generated by "stringer -type=Suit,Rank"; DO NOT EDIT.

package deck

import "strconv"

const _Suit_name = "SpadesDiamondsClubsHearts"

var _Suit_index = [...]uint8{0, 6, 14, 19, 25}

func (i Suit) String() string {
	if i < 0 || i >= Suit(len(_Suit_index)-1) {
		return "Suit(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Suit_name[_Suit_index[i]:_Suit_index[i+1]]
}

const _Rank_name = "AceOneTwoThreeFourFiveSixSevenEightNineTenJQK"

var _Rank_index = [...]uint8{0, 3, 6, 9, 14, 18, 22, 25, 30, 35, 39, 42, 43, 44, 45}

func (i Rank) String() string {
	if i < 0 || i >= Rank(len(_Rank_index)-1) {
		return "Rank(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Rank_name[_Rank_index[i]:_Rank_index[i+1]]
}
