apiVersion: v1
kind: Pod
metadata:
  name: print-username
spec:
  containers:
  - name: env-print-demo
    image: busybox   
    envFrom:
    - secretRef:
        name: test-secret
    command: ['sh', '-c', 'echo username:$(USERNAME) && sleep 3600']

# kubectl logs print-username