apiVersion: v1
kind: PersistentVolume
metadata:
  name: task-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: task-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi
---
apiVersion: v1
kind: Pod
metadata:
  name: two-containers
spec:
  restartPolicy: Never
  volumes:
  - name: shared-data
    persistentVolumeClaim:
      claimName: task-pv-claim
  containers:

  - name: debian-container
    image: debian
    volumeMounts:
    - name: shared-data
      mountPath: /pod-data
    command: ["/bin/sh"]
    args: ["-c", "echo Hello from the debian container $(date) >> /pod-data/index.html"]

  - name: busybox-container
    image: busybox
    command: ['sh', '-c', 'sleep 2 && cat /usr/share/data/index.html && sleep 3600']
    volumeMounts:
    - name: shared-data
      mountPath: /usr/share/data

# kubectl exec two-containers -c busybox-container -- /bin/cat /usr/share/data/index.html
# kubectl logs two-containers busybox-container