apiVersion : apps/v1
kind: Deployment  
metadata : 
 name: firstpod
 labels:
   app: frontend
   type: front-end
spec:
 template:
  metadata : 
    name: firstpod
    labels:
      app: frontend
      type: front-end
  spec:
    containers:
    - name: nginx-container
      image: nginx
 replicas: 3
 selector:
  matchLabels:
    type: front-end

